version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: applicationStop.sh
      timeout: 15
      runas: root
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 15
      runas:  root
  AfterInstall:
    - location: afterInstall.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: applicationStart.sh
      timeout: 15
      runas: root
  ValidateService:
    - location: validateService.sh
      timeout: 15
      runas: root