version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user
hooks:
  AfterInstall:
   - location: install_dependencies.sh
     timeout: 300
  ApplicationStart:
   - location: install_dependencies.sh
     timeout: 100
  ApplicationStop:
    timeout: 100
